services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./data:/import
    env_file:
      - .env

  grafana:
    image: grafana/grafana:11.1.0
    ports: ["3000:3000"]
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - postgres
    env_file:
      - .env

  pushgateway:
    image: quay.io/prometheus/pushgateway:v1.8.0
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - "9091:9091"

  grafana-agent:
    image: grafana/alloy:latest
    container_name: grafana-agent
    restart: unless-stopped
    depends_on:
      - pushgateway
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
    command: ["run", "/etc/alloy/config.alloy"]
    environment:
      GC_RW_URL: ${GC_RW_URL}
      GC_USERNAME: ${GC_USERNAME}
      GC_API_KEY: ${GC_API_KEY}
    env_file:
      - .env
