version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: ai-log-postgres
    environment:
      - POSTGRES_DB=siem
      - POSTGRES_USER=grafana
      - POSTGRES_PASSWORD=StrongPass123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: ai-log-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Admin123!
    depends_on:
      - postgres
    volumes:
      - ./provisioning:/etc/grafana/provisioning:ro

volumes:
  pgdata:
